### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by Saiko233** [Saiko233/furima-40791#22]
# url
https://furima-40791.onrender.com
# Basic認証のIDとパスワード
id: admin
password: 2222
# 出品者用のメールアドレスとパスワード
email: 123@qq.com
password: qq123123
# 購入者用のメールアドレスとパスワード
email: 456@qq.com
password: qq123123

**Comment by Katsuno0814** [comment]
@Saiko233 さん、FURIMAの開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、LGTMとさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_
